# Generated by Django 5.2 on 2025-04-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecordApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='TransactionType',
        ),
    ]
